package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB597)
val md_theme_dark_onPrimary = Color(0xFF591D00)
val md_theme_dark_primaryContainer = Color(0xFF7E2C00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCD)
val md_theme_dark_secondary = Color(0xFFFFB874)
val md_theme_dark_onSecondary = Color(0xFF4B2800)
val md_theme_dark_secondaryContainer = Color(0xFF6A3B00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBF)
val md_theme_dark_tertiary = Color(0xFFAAD472)
val md_theme_dark_onTertiary = Color(0xFF203600)
val md_theme_dark_tertiaryContainer = Color(0xFF314F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5F08B)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DC)
val md_theme_dark_surfaceVariant = Color(0xFF53433E)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BA)
val md_theme_dark_outline = Color(0xFFA08D86)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFFA53C00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB597)
val md_theme_dark_outlineVariant = Color(0xFF53433E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFEF5B00)